{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "cd010-app.fullname" .) }}
  labels:
    {{- include "cd010-app.labels" . | nindent 4 }}
{{- end }}
